# -*- coding: utf-8 -*-
"""Line following car.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t1O847sXGvONh7OY1XV5zVjOHYiLlUUf
"""

from machine import Pin, PWM
import time


def pin():
    a = Pin(16, Pin.OUT)
    b = Pin(4, Pin.OUT)
    c = Pin(15, Pin.OUT)
    d = Pin(2, Pin.OUT)
    l2 = Pin(26, Pin.IN)
    l1 = Pin(27, Pin.IN)
    m = Pin(14, Pin.IN)
    r1 = Pin(12, Pin.IN)
    r2 = Pin(13, Pin.IN)
    return a,b,c,d,l2,l1,m,r1,r2



def value_read(ll,l,m,r,rr):
    ll = ll.value()
    l = l.value()
    m = m.value()
    r = r.value()
    rr = rr.value()
    time.sleep_ms(10)
    p = [ll,l,m,r,rr]
    return p



def init():
    a.off()
    b.off()
    c.off()
    d.off()

def go_left():
    init()
    c.on()
    a.on()

def go_right():
    init()
    b.on()
    d.on()

def go_s():
    init()
    a.on()
    d.on()

def select(number):
    if number == 0:
        go_left()
    elif number == 1:
        go_right()
    elif number == 2:
        go_s()
    else:
        init()

def number(vr):
    s = [1,1,0,1,1]
    rr = [1,1,0,0,0]
    r = [1,1,0,0,1]
    l = [1,0,0,1,1]
    ll = [0,0,0,1,1]
    if vr == s:
        n = 2
    elif vr == rr or vr == r:
        n = 0
    elif vr == ll or vr == l:
        n =1
    else:
        n = 3
    return n



a,b,c,d,ll,l,m,r,rr = pin()

for i in range(9999):
    init()

    select(number(value_read(ll,l,m,r,rr)))
    time.sleep_ms(100)
init()